### ISSUE TITLE
Error: het toernooi is niet publiek 

### ISSUE THREAD

**Issue by stapper2000** [thepercival/fctoernooi#103]
Sinds woensdag 18-6 krijg ik, ingelogd als beheerder, de bovenstaande melding. Ik kan niet eens meer de toernooien publiek maken omdat deze opties niet meer beschikbaar zijn.

Kunt u aangeven hoe dit te verhelpen is?

Alvast bedankt voor de moeite!

Met vriendelijke groet,
Martijn Goedhart 
![Screenshot_20240619-174626_Chrome](https://github.com/thepercival/fctoernooi/assets/78502289/fda46b70-60c4-4b57-ac94-1b84c21637a3)

**Comment by thepercival** [comment]
Bedankt voor de melding. Dit is inderdaad niet juist afgehandeld. Vrijdag zal ik dit onderzoeken. Het lijkt erop dat je niet de juiste rol voor het toernooi meer hebt.

**Comment by stapper2000** [comment]
Hoi Coen,Dank voor de snelle reactie en dat je dit op wilt pakken.Er leuke software en handig ook.Alvast bedankt!Gr.Martijn Op 19 jun. 2024 23:29 schreef Coen Dunnink ***@***.***>:
Bedankt voor de melding. Dit is inderdaad niet juist afgehandeld. Vrijdag zal ik dit onderzoeken. Het lijkt erop dat je niet de juiste rol voor het toernooi meer hebt.

**Comment by Steffanewouds** [comment]
Ik heb inderdaad exact hetzelfde probleem! Zou dit z.s.m. gefixt kunnen worden? Wij hebben aanstaande zaterdag een toernooi wat geheel is opgezet met jullie software! Wij maken er al 3 jaar op rij met zéér veel plezier gebruik van!

**Comment by Steffanewouds** [comment]
Bijbehorend e-mail adres bij bovenstaand probleem is kwadijksixen@gmail.com

**Comment by thepercival** [comment]
na een refresh(F5) zou de foutmelding verdwenen moeten zijn. Bedankt voor het melding. Succes met jullie toernooien.

**Comment by Steffanewouds** [comment]
Het is inderdaad gefixt! Wat een top service! Hebben jullie een donatiebox o.i.d. ? Petje af!

**Comment by thepercival** [comment]
nee, we hebben geen dontatiebox. Wanneer je feedback hebt of tips voor verbeteringen dan zou dat ook heel waardevol zijn. Je kunt dit hier melden of via info@fctoernooi.nl.

Alvast bedankt daarvoor.
