### ISSUE TITLE
Hoe kun je onderling resultaat boven doelsaldo laten gelden bij gelijke stand in de poule

### ISSUE THREAD

**Issue by Snoeren1970** [thepercival/fctoernooi#56]
Hoe kun je onderling resultaat boven doelsaldo laten gelden bij gelijke stand in de poule

**Comment by thepercival** [comment]
In het beheer gedeelte, ga je naar de sport. Dan naar de tab puntentelling. Dan de knop rangschikking. Dit kan je alleen aanpassen als er nog geen wedstrijden zijn gespeeld. Hopelijk lukt het zo.

**Comment by Snoeren1970** [comment]
Ja dit werkt, dank je
