### ISSUE TITLE
poule 5 teams

### ISSUE THREAD

**Issue by Snoeren1970** [thepercival/fctoernooi#60]
Ik heb in een toernooi 2 poules van 5 teams.
na de 1e poulefase gaan de nr's 5 tegen elkaar, nr's 4, nr's 3, nr's 2 en nr's 1
hoe krijg ik dit in het schema ingedeeld ?

**Comment by thepercival** [comment]
Je kunt op de knop "kwalificatie groepen" drukken. Dan kun je de nummers 1,
2, etc. apart tegen elkaar laten spelen.

Groet Coen

**Comment by Snoeren1970** [comment]
Dag Coen,

Ik weet niet wat ik dan bij winnaar en verliezers moet invullen.
ik kom nergens tot 5 wedstrijden (A1-B1, A2-B2 etc)

groet,

Arno

Op do 17 jun. 2021 om 15:22 schreef Coen Dunnink ***@***.***>:

> Je kunt op de knop "kwalificatie groepen" drukken. Dan kun je de nummers 1,
> 2, etc. apart tegen elkaar laten spelen.
>
> Groet Coen
>

**Comment by thepercival** [comment]
Je moet dan de volgende structuur maken

![Schermafdruk van 2021-06-17 15-49-17](https://user-images.githubusercontent.com/1693544/122409757-b0466180-cf83-11eb-9607-c13b8e686545.png)

**Comment by Snoeren1970** [comment]
jaaaa, gelukt.
dank je

Op do 17 jun. 2021 om 15:50 schreef Coen Dunnink ***@***.***>:
