### ISSUE TITLE
Link in QR-code bestaat niet op website

### ISSUE THREAD

**Issue by michaelblaas** [thepercival/fctoernooi#65]
Op de wedstrijd-briefjes wordt een QR-code geprint. Deze code bevat de volgende link naar de wedstrijd:
https://fctoernooi.nl/admin/game/toernooi-nr/wedstrijd-nr
Deze link geeft geen geldig resultaat.

Als je via de site naar de betreffende wedstrijd gaat is de link:
De juiste link moet zijn: 
https://fctoernooi.nl/admin/gameagainst/toernooi-nr/wedstrijd-nr

Voorgestelde oplossing: aan de sitekant een alias toevoegen voor het /gameagainst kruimelpad. Dan gaan reeds geprinte QR-codes alsnog werken en kunnen uitslagen snel worden ingevoerd.

(hopelijk lukt dit voor ons toernooi op 18 juni :-)

**Comment by thepercival** [comment]
het toevoegen van de url suffix is niet doorgevoerd voor de pdf. Dit is nu hersteld.
Het doorlinken via qr-code zou weer moeten werken.

Bedankt voor de melding!

**Comment by michaelblaas** [comment]
Dank voor de supersnelle reparatie! Nu kan het toernooi helemaal niet meer stuk! Top applicatie!
