### ISSUE TITLE
wedstrijden inplannen per poule

### ISSUE THREAD

**Issue by thepercival** [thepercival/fctoernooi#73]
wedstrijden inplannen per poule
dus eerst speelronde 1 van elke poule , daarna speelronde 2 van elke poule, etc.

**Comment by thepercival** [comment]
Is gerealiseerd. Door een optie toe te voegen aan het wedstrijd planning instellingen scherm. Dat is een hele term. Ik zal een afdruk toe voegen

**Comment by thepercival** [comment]
![Schermafdruk van 2023-01-29 16-22-10](https://user-images.githubusercontent.com/1693544/215336373-9246c5cb-f73b-4285-b87d-0cb74f510794.png)

**Comment by Coolcatss** [comment]
<img width="345" alt="image" src="https://github.com/thepercival/fctoernooi/assets/57798729/53b19b60-fa8a-44c6-bb98-cb7a0c21cba1">

Ik heb de optie aangevinkt maar het werkt nog niet helaas.

**Comment by thepercival** [comment]
De optie is niet "per poule" , maar "per poule en wedstrijdronde". Dus alle wedstrijden van poule A en dan alle wedstrijden van poule B is niet mogelijk met "automatisch plannen"
