### ISSUE TITLE
Wedstrijden ingedeeld per poule

### ISSUE THREAD

**Issue by Coolcatss** [thepercival/fctoernooi#78]
Bij het spelen met 2 poules speelt eerst poule A een wedstrijd en dan meteen poule B en zo steeds door.

Het liefst laat ik eerst poule A alle wedstrijden spelen en daarna pas poule B aangezien ik maar 1 veld beschikbaar heb en ik niet iedereen al aanwezig wil laten zijn. 

Ik heb nu alles handmatig moeten omzetten maar dit zou een hele handige toevoeging kunnen zijn!

Voorbeeld: https://fctoernooi.nl/14073

**Comment by thepercival** [comment]
bedankt voor de melding, dit was ook een vraag van iemand anders.

https://github.com/thepercival/fctoernooi/issues/73

Deze maand is er een update naar productie en zal dit mogelijk zijn.
