### ISSUE TITLE
Live scorebord - Tijden niet zichtbaar

### ISSUE THREAD

**Issue by Coolcatss** [thepercival/fctoernooi#79]
Het is momenteel niet mogelijk om de speeltijd van de wedstrijden te zien op het live scorebord. Nu weten de teams niet hoe laat ze moeten spelen.

**Comment by thepercival** [comment]
Deze is inmiddels zichtbaar. 

Techniek:
Batchviewmode nakijken

**Comment by thepercival** [comment]
techniek ook aangepast
