### ISSUE TITLE
deelnemers als scheidsrechter werkt niet goed

### ISSUE THREAD

**Issue by Sjak-Baten** [thepercival/fctoernooi#93]
Hallo,
Het automatisch scheidsrechter toekennen (deelnemers als scheidsrechter) werkt deze keer niet goed. Er worden scheidsrechters geselecteerd die op dat moment zelf moeten spelen. Ook gebeurt het dat de zelfde scheidsrechter drie maal achter elkaar aan de beurt is. Betreft een jaarlijks Jeu de Boules toernooi wat al eerder (twee jaar) wel goed werkte. Ik heb ook de twee vorige versies geopend en die kloppen nu ook niet meer. Hopelijk kunt u mij hierbij helpen, bij voorbaat dank voor de genomen moeite.
M.vr.gr.
Sjak Baten

**Comment by thepercival** [comment]
Hallo Sjak,

Dat is vervelend. Dinsdag pakken we deze issue op en kunnen het dan hopelijk ook direct oplossen.

**Comment by Sjak-Baten** [comment]
Hallo Coen,

Dank voor jullie vlotte reactie, hopelijk gaat het lukken want donderdag is het toernooi al.
Alvast goed weekend gewenst.

M.vr.gr.
Sjak Baten

________________________________
Van: Coen Dunnink ***@***.***>
Verzonden: vrijdag 3 mei 2024 14:25
Aan: thepercival/fctoernooi ***@***.***>
CC: Sjak-Baten ***@***.***>; Author ***@***.***>
Onderwerp: Re: [thepercival/fctoernooi] deelnemers als scheidsrechter werkt niet goed (Issue #93)


Hallo Sjak,

Dat is vervelend. Dinsdag pakken we deze issue op en kunnen het dan hopelijk ook direct oplossen.

**Comment by thepercival** [comment]
De scheidsrechter-als-deelnemer werd niet goed getoond. De juiste scheidsrechter zou nu juist moeten worden getoond. Zou je een reactie kunnen geven of het nu correct is. Alvast bedankt

**Comment by Sjak-Baten** [comment]
Hallo Coen,

Het werkt weer zoals voorheen, erg bedankt voor het oplossen van dit probleem.
Wij zijn er erg blij mee dat het zo snel opgelost kon worden. 👍

Met vriendelijke groet,
Stichting Dorpsweek Standdaarbuiten
Sjak Baten

________________________________
Van: Coen Dunnink ***@***.***>
Verzonden: dinsdag 7 mei 2024 09:49
Aan: thepercival/fctoernooi ***@***.***>
CC: Sjak-Baten ***@***.***>; Author ***@***.***>
Onderwerp: Re: [thepercival/fctoernooi] deelnemers als scheidsrechter werkt niet goed (Issue #93)


De scheidsrechter-als-deelnemer werd niet goed getoond. De juiste scheidsrechter zou nu juist moeten worden getoond. Zou je een reactie kunnen geven of het nu correct is. Alvast bedankt
