### ISSUE TITLE
Eindstand incorrect bij 2 poules met extra ronde

### ISSUE THREAD

**Issue by kdbruin** [thepercival/fctoernooi#98]
Voor ons laatste toernooi hebben we 2 poules met 4 teams en na de reguliere wedstrijden (elk team speelt 1x tegen elkaar) heb ik een extra ronde toegevoegd waarbij de nummers 1 van elke poule tegen elkaar spelen, net als de nummers 2, 3 en 4.

De standen voor de eerste ronde zijn correct maar na het spelen van de tweede ronde is de eindstand niet correct. Bijvoorbeeld in de eindstand staat team Caeciliaschool 2 bovenaan terwijl ze de wedstrijd om de 1e/2e plek hebben verloren.

Zie het toenooi met ID=21686.

**Comment by thepercival** [comment]
Bedankt voor het melden van de bug. In de ontwikkel-omgeving is het probleem verholpen. De verwachting is dat de bug over 1 a 2 weken wordt opgenomen in de huidige productie omgeving a.k.a. fctoernooi.nl

Zie hieronder een schermafdruk bij het openen van de eindstand op de test-omgeving

![image](https://github.com/thepercival/fctoernooi/assets/1693544/10ebf084-eb88-4cce-b132-cff086021256)
